### ISSUE TITLE
Issue with using candlestick chart

### ISSUE THREAD

**Issue by d-amit** [apexcharts/ng-apexcharts#28] opened 2019-10-08 15:36 UTC
I've posted my issue with apex-chart as well just in case...

https://github.com/apexcharts/apexcharts.js/issues/975

But for some reason, the xaxis tooltip is stuck in place. Also notice how when I zoom in, the candles do NOT scale accordingly. Please let me know if Im missing a config or if I have conflicting configs setup. See link above for config details.

![stock_chart_issues](https://user-images.githubusercontent.com/14062379/66410254-cbe02300-e9bf-11e9-9934-ffa128a57967.gif)

**Comment by junedchhipa** [comment] 2020-01-15 05:32
Closing as duplicate of apexcharts/apexcharts.js#975

**Closed by junedchhipa** 2020-01-15 05:32 UTC
